name: Build Windows Test

on:
  workflow_dispatch:

jobs:
  build_windows:
    name: 🪟 Build Windows
    runs-on: windows-latest
    steps:
      - name: 📱️Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          channel: 'stable'
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - name: 🧹 Clean
        run: flutter clean
      - name: ⬇️ Get dependencies
        run: flutter pub get
      - name: 🪟 Build Windows
        run: |
          flutter build windows
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          path: build/windows/runner/Release/
          type: 'zip'
          filename: 'pokedex-windows.zip'
      - name: ⬆️ Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: pokedex-windows.zip
          path: pokedex-windows.zip
