# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Web Deploy on GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
      
      - name: Install Dependencies
        run: flutter pub get
        
      - name: Build Flutter Web
        run: flutter build web --web-renderer html
        
      - name: Deploy to GitHub Pages
        run: |
          git clone https://${{secrets.TOKEN}}@github.com/alanlgoncalves/pokedex-web-release.git
          cp -r build/web/. pokedex-web-release
          cd pokedex-web-release
          git config --global user.email alan.lgoncalves@outlook.com
          git config --global user.name alanlgoncalves
          git add .
          git commit -m "New release"
          git push https://${{secrets.TOKEN}}@github.com/alanlgoncalves/pokedex-web-release.git master
